// sites/web/src/start-with-renderer/App.vue
<template>
  <GenuiConfigProvider :materials="materials">
    <div class="demo-container">
      <div class="input-group">
        <input v-model="inputText" placeholder="请输入问题..." @keyup.enter="handleSend" />
        <button @click="handleSend">发送</button>
      </div>
      <GenuiRenderer :content="schema" :key="rendererKey" />
    </div>
  </GenuiConfigProvider>
</template>

<script setup lang="ts">
import { ref } from 'vue';
import { GenuiRenderer } from '@opentiny/genui-sdk-vue/renderer';
import { GenuiConfigProvider } from '@opentiny/genui-sdk-vue/config-provider';
import { materials } from '@opentiny/genui-sdk-materials-vue-opentiny-vue/materials';
import { fetchSchemaStream } from './fetch-schema-stream';

const inputText = ref('');
const schema = ref<any>({ componentName: 'Page', children: [] });
const rendererKey = ref(0);
const generating = ref(false);

const handleSend = async () => {
  if (!inputText.value.trim() || generating.value) return;

  generating.value = true;
  schema.value = '';
  rendererKey.value++;
  const userInput = inputText.value;
  inputText.value = '';

  try {
    await fetchSchemaStream('http://localhost:3100/chat/completions', userInput, (schemaChunk) => {
      schema.value += schemaChunk;
    });
  } catch (error) {
    console.error('请求失败:', error);
  } finally {
    generating.value = false;
  }
};
</script>

<style scoped>
.demo-container {
  padding: 16px;
  box-sizing: border-box;
}

.input-group {
  display: flex;
  gap: 8px;
  margin-bottom: 16px;
}

input {
  flex: 1;
  padding: 8px 12px;
  border: 1px solid #ddd;
  border-radius: 4px;
}

button {
  padding: 8px 16px;
  background: #1890ff;
  color: white;
  border: none;
  border-radius: 4px;
  cursor: pointer;
}
</style>

// sites/genui-react/src/App.tsx
import { useRef, useState, type KeyboardEvent } from 'react';
import { genPrompt } from '@opentiny/genui-sdk-core';
import { GenuiConfigProvider, GenuiRenderer } from '@opentiny/genui-sdk-react';
import { materials } from '@opentiny/genui-sdk-materials-react-antd/materials';
import { materialsMeta } from '@opentiny/genui-sdk-materials-react-antd/meta';
import { fetchSchemaStream } from './fetch-schema-stream';
import './App.css';

const systemPrompt = genPrompt('React', materialsMeta);

function App() {
  const [inputText, setInputText] = useState('');
  const [schema, setSchema] = useState('');
  const [rendererKey, setRendererKey] = useState(0);
  const generatingRef = useRef(false);

  const handleSend = async () => {
    if (!inputText.trim() || generatingRef.current) return;

    const baseURL = import.meta.env.VITE_BASE_URL as string | undefined;
    const apiKey = import.meta.env.VITE_API_KEY as string | undefined;
    const model = (import.meta.env.VITE_MODEL as string | undefined) || 'deepseek-v4-flash';

    if (!baseURL || !apiKey) {
      console.error('请先配置 VITE_BASE_URL 与 VITE_API_KEY（可参考 .env.example）');
      return;
    }

    generatingRef.current = true;
    setSchema('');
    setRendererKey((key) => key + 1);
    const userInput = inputText;
    setInputText('');

    try {
      await fetchSchemaStream(
        userInput,
        (schemaChunk) => {
          setSchema((prev) => prev + schemaChunk);
        },
        { baseURL, apiKey, model, systemPrompt },
      );
    } catch (error) {
      console.error('请求失败:', error);
    } finally {
      generatingRef.current = false;
    }
  };

  const handleKeyUp = (event: KeyboardEvent<HTMLInputElement>) => {
    if (event.key === 'Enter') {
      void handleSend();
    }
  };

  return (
    <GenuiConfigProvider materials={materials}>
      <div className="demo-container">
        <div className="input-group">
          <input
            value={inputText}
            placeholder="请输入问题..."
            onChange={(event) => setInputText(event.target.value)}
            onKeyUp={handleKeyUp}
          />
          <button type="button" onClick={() => void handleSend()}>
            发送
          </button>
        </div>
        <GenuiRenderer key={rendererKey} content={schema} />
      </div>
    </GenuiConfigProvider>
  );
}

export default App;
